name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build Geminio
        run: ./gradlew plugins:hh-geminio:buildPlugin -DsystemProp.productType=ANDROID_STUDIO_ARCTIC_FOX
