name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Download Android Studio
        run: |
          wget -q https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2020.3.1.25/android-studio-2020.3.1.25-linux.tar.gz
          mkdir androidstudio
          tar -xf android-studio-2020.3.1.25-linux.tar.gz -C ./androidstudio/
          ls ./androidstudio/android-studio
          ls "$(pwd)/androidstudio/android-studio"
      - name: Build Geminio
        run: ./gradlew plugins:hh-geminio:buildPlugin -DandroidStudioPath="$(pwd)/androidstudio/android-studio"
