name: Publish plugins artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - release-canary-*

jobs:
  build:
    name: Build all plugins
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build plugins
        run: |
          ./gradlew buildAllPlugins -DandroidStudioPath
      - name: Publish plugins
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/plugins/hh-carnival.zip
            build/plugins/hh-garcon.zip
            build/plugins/hh-geminio.zip
          tag_name: build-${{ github.run_number }}
          name: Build №${{ github.run_number }}
          draft: false
          prerelease: true
